server:
  port: 8090

spring:
  application:
    name: cooRoot
#  profiles:
#    active: ${SPRING_APPLICATION_PROFILES_ACTIVE:}
#    include: >
#      logging,
#      custom,
#      integration

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_SCHEMA:cooroot}
    username: ${DB_USERNAME:alex_roosevelt}
    password: ${DB_PASSWORD:postgres}
  flyway:
    user: ${DB_USERNAME:alex_roosevelt}
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_SCHEMA:cooroot}
    locations: db/migration


